projects/diw-evu%2Fdieter_public%2Fdieterpy/repository/commits: 6
projects/dlr-ve%2Fesy%2Famiris%2Famiris/issues: 5
projects/dlr-ve%2Fesy%2Famiris%2Famiris/merge_requests: 5
projects/dlr-ve%2Fesy%2Famiris%2Famiris/repository/commits: 15
projects/dlr-ve%2Fesy%2Fremix%2Fframework/repository/commits: 49
projects/energyincities%2Fpython-ehub/repository/commits: 7
projects/fame-framework%2Ffame-core/issues: 4
projects/fame-framework%2Ffame-core/merge_requests: 4
projects/fame-framework%2Ffame-core/merge_requests/119/notes: 2
projects/fame-framework%2Ffame-core/repository/commits: 9
projects/fame-framework%2Ffame-io/issues: 5
projects/fame-framework%2Ffame-io/merge_requests: 5
projects/fame-framework%2Ffame-io/repository/commits: 14
projects/mosaik%2Fmosaik/issues: 4
projects/mosaik%2Fmosaik/merge_requests: 4
projects/mosaik%2Fmosaik/merge_requests/153/notes: 2
projects/mosaik%2Fmosaik/merge_requests/213/notes: 2
projects/mosaik%2Fmosaik/repository/commits: 17
projects/sesit%2Fcopper/issues: 4
projects/sesit%2Fcopper/repository/commits: 8
projects/sesit%2Fidea/repository/commits: 5
projects/sesit%2Fsilver/repository/commits: 3
projects/smartgridtoolbox%2Fsmartgridtoolbox/repository/commits: 7
projects/smspp%2Fsmspp-project/repository/commits: 19
